### ISSUE TITLE
终末之诗

### ISSUE THREAD

**Issue by yuxwd** [MC-Schale-Server/Resource-packs#1]
终末之诗可以修改一下吗？
感觉有点奇怪，可以加点BA的元素？-Others/End_Poem/end3.txt
BA终章的文字怎么样。

**Comment by TPOD14077** [comment]
> 终末之诗可以修改一下吗？
> 感觉有点奇怪，可以加点BA的元素？-Others/End_Poem/end3.txt
> BA终章的文字怎么样。

计划中的内容哟

**Comment by TPOD14077** [comment]
计划在5月修改

**Comment by TPOD14077** [comment]
已在构建版中完成修改，基岩版无法修改，仅在java版中作了修改
